/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATRICE_H_RPCGEN
#define _CALCULATRICE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct variable {
	double a;
	double b;
};
typedef struct variable variable;


#define CALCUL 0x20000001
#define PROG_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADDITION 1
extern  double * addition_1(variable *, CLIENT *);
extern  double * addition_1_svc(variable *, struct svc_req *);
#define SOUSTRACT 2
extern  double * soustract_1(variable *, CLIENT *);
extern  double * soustract_1_svc(variable *, struct svc_req *);
#define MULTIPLICAT 3
extern  double * multiplicat_1(variable *, CLIENT *);
extern  double * multiplicat_1_svc(variable *, struct svc_req *);
#define DIVIS 4
extern  double * divis_1(variable *, CLIENT *);
extern  double * divis_1_svc(variable *, struct svc_req *);
extern int calcul_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADDITION 1
extern  double * addition_1();
extern  double * addition_1_svc();
#define SOUSTRACT 2
extern  double * soustract_1();
extern  double * soustract_1_svc();
#define MULTIPLICAT 3
extern  double * multiplicat_1();
extern  double * multiplicat_1_svc();
#define DIVIS 4
extern  double * divis_1();
extern  double * divis_1_svc();
extern int calcul_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_variable (XDR *, variable*);
extern  bool_t xdr_variable (XDR *, variable*);

#else /* K&R C */
extern bool_t xdr_variable ();
extern bool_t xdr_variable ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATRICE_H_RPCGEN */
