/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculatrice.h"

double *
addition_1_svc(variable *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result=argp->a+argp->b;
	return &result;
}

double *
soustract_1_svc(variable *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result=argp->a-argp->b;
	return &result;
}

double *
multiplicat_1_svc(variable *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result=argp->a*argp->b;
	return &result;
}

double *
divis_1_svc(variable *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result=argp->a/argp->b;
	return &result;
}
